# Generated by Django 5.2.8 on 2026-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="persona",
            field=models.CharField(
                choices=[
                    ("business", "Business"),
                    ("bro", "Bro"),
                    ("flirty", "Flirty"),
                    ("futurebot", "Futurebot"),
                    ("butler", "Butler"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
    ]
