# Generated by Django 5.2.1 on 2025-10-03 12:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "conversation_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Conversation", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_input_tokens", models.IntegerField(default=0)),
                ("total_output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
            ],
            options={
                "db_table": "ai_assistant_conversation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ai_assistan_created_6fb407_idx"
                    ),
                    models.Index(
                        fields=["conversation_id"],
                        name="ai_assistan_convers_092552_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "text_format",
                    models.CharField(
                        choices=[
                            ("plain", "Plain"),
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("voice", "Voice"),
                        ],
                        default="plain",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("metadata_json", models.JSONField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "previous_message_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("model", models.CharField(blank=True, max_length=100, null=True)),
                ("llm_model", models.CharField(blank=True, max_length=100, null=True)),
                ("input_tokens", models.IntegerField(blank=True, null=True)),
                ("input_cached_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(blank=True, null=True)),
                ("output_reasoning_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_assistant.conversation",
                    ),
                ),
            ],
            options={
                "db_table": "ai_assistant_message",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation", "created_at"],
                        name="ai_assistan_convers_8f1a44_idx",
                    ),
                    models.Index(
                        fields=["message_id"], name="ai_assistan_message_81e6f0_idx"
                    ),
                    models.Index(fields=["role"], name="ai_assistan_role_804f57_idx"),
                    models.Index(
                        fields=["-created_at"], name="ai_assistan_created_31802c_idx"
                    ),
                ],
            },
        ),
    ]
