# Generated by Django 5.2.8 on 2026-03-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0006_remove_message_text_format_alter_message_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="pipeline_steps",
            field=models.JSONField(default=list),
        ),
    ]
