# Generated by Django 5.2.8 on 2026-07-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0008_add_pipeline_trace_to_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conversation_id", models.CharField(db_index=True, max_length=255)),
                ("message_id", models.CharField(db_index=True, max_length=255)),
                (
                    "previous_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField()),
                ("user_text", models.TextField(blank=True)),
                ("ai_text", models.TextField(blank=True)),
                (
                    "jira_key",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "ai_assistant_conversationflag",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ai_assistan_created_9cddd3_idx"
                    ),
                    models.Index(
                        fields=["severity"], name="ai_assistan_severit_215aab_idx"
                    ),
                    models.Index(
                        fields=["reviewed_at"], name="ai_assistan_reviewe_4ae498_idx"
                    ),
                    models.Index(
                        fields=["conversation_id"],
                        name="ai_assistan_convers_944bdb_idx",
                    ),
                ],
            },
        ),
    ]
