# Generated by Django 5.2.8 on 2026-09-13 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0009_conversationflag"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageAudio",
            fields=[
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="audio",
                        serialize=False,
                        to="ai_assistant.message",
                    ),
                ),
                ("audio", models.BinaryField()),
                ("content_type", models.CharField(default="audio/webm", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "ai_assistant_message_audio",
            },
        ),
    ]
