# Generated by Django 5.2.8 on 2026-10-04 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0010_messageaudio"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("image", models.BinaryField()),
                ("content_type", models.CharField(default="image/jpeg", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ai_assistant.message",
                    ),
                ),
            ],
            options={
                "db_table": "ai_assistant_message_image",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "position"),
                        name="unique_message_image_position",
                    )
                ],
            },
        ),
    ]
