# Generated by Django 5.2.8 on 2026-10-04 21:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0011_messageimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        default="application/octet-stream", max_length=100
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("data", models.BinaryField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="ai_assistant.message",
                    ),
                ),
            ],
            options={
                "db_table": "ai_assistant_message_file",
                "ordering": ["position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("message", "position"),
                        name="unique_message_file_position",
                    )
                ],
            },
        ),
    ]
